### ISSUE TITLE
how to merge ip range to ips and mask?

### ISSUE THREAD

**Issue by douloveppt** [go4org/netipx#2]
like this:
Range(192.168.11.11-192.168.11.11)  ==>  IP(192.168.11.11)
Range(192.168.12.0-192.168.12.255)  ==>  NETWORK(192.168.12.0/24)

thank you so much ! ! !

**Comment by bradfitz** [comment]
Start with an IPSetBuilder: https://pkg.go.dev/go4.org/netipx#IPSetBuilder

Then add stuff to it.

Then build a set: https://pkg.go.dev/go4.org/netipx#IPSetBuilder.IPSet

And then ask that IPSet for its prefixes: https://pkg.go.dev/go4.org/netipx#IPSet.Prefixes

Some of the prefixes might be a single IP: https://pkg.go.dev/net/netip#Prefix.IsSingleIP
